debian

diff --git a/dockerfiles/Dockerfile.debian.bullseye.masscan b/dockerfiles/Dockerfile.debian.bullseye.masscan
--- a/dockerfiles/Dockerfile.debian.bullseye.masscan
+++ b/dockerfiles/Dockerfile.debian.bullseye.masscan
@@ -11,6 +11,11 @@ RUN set -xe && \
     apt-get autoremove - && \
     apt-get clean 
 
+#FAIL: failed to load libpcap shared library
+#[hint]: you must install libpcap or WinPcap
+RUN set -xe && \
+    apt-get install libpcap-dev -y
+
 # https://github.com/robertdavidgraham/masscan
 RUN set -xe && \
     apt-get install -y git make gcc && \
